export const FrontData = [
  {
    id: '1-1',
    title: "17 Watching",
    description: "將我的片單寫成網頁方便分享推薦",
    skill: "React / NextJS",
    img: 'pic1.png',
    link: "https://nextjs-video-list-app.vercel.app",
  },
  {
    id: '1-2',
    title: "蘋果菜果園",
    description: "送給朋友的生日小猜謎",
    skill: "React / NextJS",
    img: 'pic2.png',
    link: "https://nextjs-hbd-game-apple.vercel.app/welcome",
  },
  {
    id: '1-3',
    title: "客話學習網",
    description: "與教育界合作的推廣客家話學習網",
    skill: "React / NextJS",
    img: 'pic3.png',
    link: "https://kids.hakka.gov.tw/",
  },
  {
    id: '1-4',
    title: "家具估價系統",
    description: "為系統家具公司客製估價網站",
    skill: "React / NextJS",
    img: 'pic4.png',
    link: "https://nextjs-furniture-app.vercel.app",
  },
  {
    id: '1-5',
    title: "React Meetups",
    description: "Next寫的第一個集會列表網站",
    skill: "NextJS / MongoDB",
    img: 'pic5.png',
    link: "https://nextjs-meetup-app-psi.vercel.app",
  },
  {
    id: '1-6',
    title: "React Store",
    description: "React寫的第一個購物網站",
    skill: "React / Axios",
    img: 'pic6.png',
    link: "https://react-store-ashen.vercel.app",
  },
];

export const PyData = [
  {
    id: '2-1',
    title: "AI人臉辨識點名系統",
    description: "串接 AWS Rekognition API 辨識人臉建立課堂點名系統",
    skill: "Python / AWS Rekognition",
    img: 'pic7.png',
    link: "https://github.com/59417/AWS_FaceComparison/blob/main/CompareFace.pdf",
  },
  {
    id: '2-2',
    title: "AI口罩偵測預測模型",
    description: "YOLOv4演算法深度學習建立口罩偵測模型",
    skill: "Python / Yolo Deep Learning",
    img: 'pic8.png',
    link: "https://github.com/59417/YOLOv4_MaskDetect/blob/main/Yolov4_mask.pdf",
  },
  {
    id: '2-3',
    title: "AI食道癌影像偵測",
    description: "將 OpenCV 應用於MRI照片自動偵測腫瘤位置",
    skill: "Python / OpenCV",
    img: 'pic9.png',
    link: "https://github.com/59417/OpenCV_tumor/blob/main/AI%E9%A3%9F%E9%81%93%E7%99%8C%E5%BD%B1%E5%83%8F%E5%81%B5%E6%B8%AC%E5%B0%88%E6%A1%88%20.pdf",
  },
];
