import Head from 'next/head';
// import Image from 'next/image';
import { Fragment } from 'react';
import classes from '../styles/Home.module.css';
import Header from '../components/header/Header';
import About from '../components/body/About'; 
import FrontendList from '../components/body/FrontendList';
import PythonList from '../components/body/PythonList';


export default function Homepage() {
    return (
        <Fragment>
           <Head>
                <title>Yi-Ching Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="initial-scale=1.0, width=device-width" />
                <link rel="icon" href="/17icon.png" />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
            </Head>

            <header className={classes.header}>
                <Header/>
            </header>
                
            <main className={classes.main}>
                <div className={classes.body_container}><About/></div>
                <div className={classes.body_container}><FrontendList/></div>
                <div className={classes.body_container}><PythonList/></div>
            </main>

            <footer className={classes.footer}>
                <a
                    href="https://github.com/59417"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    &copy; 2022 Yi-Ching
                    <span className={classes.logo}>
                        <i className="fab fa-github"></i>
                    </span>
                </a>
            </footer> 
        </Fragment>
    );
};